# NumPy Exercises 



#### Import NumPy as np

In [2]:
import numpy as np

#### Create an array of 10 zeros 

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [16]:
slice_of_arr = arr[0:10]

#show slice
slice_of_arr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [12]:
arr = np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [10]:
arr = np.arange(10,50,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [19]:
my_matrix = [[0,1,2],[3,4,5],[6,7,8]]
my_matrix
y=np.array(my_matrix)
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [20]:
np.random.rand(1)

array([0.57386805])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [21]:
np.random.rand(5,5)

array([[0.81808005, 0.62993112, 0.36810635, 0.35829144, 0.06938256],
       [0.44146883, 0.62885327, 0.27633178, 0.75532068, 0.22737463],
       [0.95971266, 0.01037544, 0.40579139, 0.47040117, 0.55037664],
       [0.292382  , 0.70889796, 0.85578074, 0.88670596, 0.23949563],
       [0.48288527, 0.90916543, 0.59955203, 0.72874614, 0.82803361]])

#### Create the following matrix:

In [3]:
import numpy as np
np.random.rand(10,10)

array([[0.92012656, 0.70877032, 0.29312886, 0.82346288, 0.94439837,
        0.52445138, 0.6757421 , 0.81987756, 0.7071115 , 0.04353459],
       [0.14095382, 0.53991466, 0.02812511, 0.87049633, 0.65194919,
        0.58926902, 0.21413317, 0.17151598, 0.58439147, 0.33677953],
       [0.01975189, 0.47115913, 0.63442774, 0.96424765, 0.25324749,
        0.3494512 , 0.77049561, 0.01845355, 0.72272383, 0.80559178],
       [0.52438432, 0.34463947, 0.78391458, 0.0701958 , 0.64961221,
        0.96119784, 0.76608889, 0.92782274, 0.10351724, 0.09482132],
       [0.65245408, 0.81495465, 0.48173604, 0.99216158, 0.53655752,
        0.81545126, 0.02858699, 0.33131016, 0.9815772 , 0.92889693],
       [0.5818865 , 0.94654865, 0.53825408, 0.06708032, 0.63222128,
        0.79365581, 0.1136175 , 0.19653977, 0.25376052, 0.64229297],
       [0.05225136, 0.64172795, 0.65735692, 0.51800161, 0.04534991,
        0.2432902 , 0.64432524, 0.40425703, 0.95083112, 0.63717042],
       [0.79060754, 0.26241439, 0.9191380

#### Create an array of 20 linearly spaced points between 0 and 1:

In [22]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [5]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [6]:
mat[1:,1:]

array([[ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [7]:
mat[3,4]


20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [12]:
mat[1:4,1]

array([ 7, 12, 17])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [13]:
mat[4]

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [17]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [30]:
x = np.sum(mat)

x

325

#### Get the standard deviation of the values in mat

In [27]:
mat=np.arange(1,26)
x=np.std(mat)  
x

7.211102550927978

#### Get the sum of all the columns in mat

In [29]:
mat = np.arange(1,26).reshape(5,5)
x = np.sum(mat, axis=0)         #sum of all columns
x

array([55, 60, 65, 70, 75])

# Great Job!