## Write a Numpy program to compute the multiplication of two given matrixes

In [65]:
import numpy as np 

# input two matrices 
mat1 = ([1,2,3],[4 ,5,6],[6,9,5]) 
mat2 = ([6,7,8],[4,8,9],[2,3,5]) 
  
# return dot product 
x= np.dot(mat1,mat2) 
  
# print matrix
x

array([[ 20,  32,  41],
       [ 56,  86, 107],
       [ 82, 129, 154]])

## Write a NumPy program to compute the determinant of a given square array

In [44]:
my_list = [2,3,4]
import numpy as np
np.array(my_list)

array([2, 3, 4])

In [46]:
np.sqrt(my_list)        #given square array

array([1.41421356, 1.73205081, 2.        ])

## Write a NumPy program to compute the cross product of two given vectors

In [52]:
import numpy as np

#initialize arrays
A = [2,3]
B = [5,6]

#cross product
x = np.cross(A,B)
x

array(-3)

## Write a NumPy program to compute the condition number of a given matrix

## Write a NumPy program to compute the inverse of a given matrix

In [57]:
import numpy as np 
    
# Inverse of given matrix

A = np.array([[1, 2], [3, 4]])           
 
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]
